# Generated by Django 3.1.2 on 2020-10-21 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compañia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compañia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descirpcion', models.TextField(help_text='Inserte una descripcion del juego', max_length=1000)),
                ('compañia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Aplicacion.compañia')),
                ('genero', models.ManyToManyField(to='Aplicacion.Genero')),
            ],
        ),
    ]
