# Generated by Django 3.1.2 on 2020-10-21 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Juego',
        ),
    ]
